### PR TITLE
Staff view displays all keys for mixed key arrays.

### PR DESCRIPTION
**Pull request by natecollins**

### CODE REVIEW

**Review by demiankatz — CHANGES_REQUESTED** [review]
@natecollins, I just tested this out, and unfortunately, it doesn't actually solve the problem I'm seeing. That's because the array structure isn't quite what I thought... It's an array of arrays, with each subarray containing a single key. So if the subarray is keyed with something like '049' it displays but if the key is something like '100' it does not display.

To illustrate, it's something like this:

```
[
    ['049' => ['value1'],
    ['100' => ['value2'],
]
```

If we changed the heuristic to match the new array_is_list function that you mentioned, I think that would solve my current use case, but I'm not sure if there are other cases that would become worse. What do you think? (The other advantage to following array_is_list behavior is that we could put in a TODO to simplify the code after raising the minimum PHP version to 8, which I expect should happen fairly soon after we release VuFind 9.0).

What do you think?

**Comment by natecollins** [comment]
@demiankatz Ah, I understand now. Thanks for the example. As PHP casts those string-integer keys into true integers, performing simple `is_int()` checks becomes a problem. The logic in `array_is_list()` should do a good job of avoiding the mistaken hiding of int-like keys.

The latest revision is pushed and it's using `array_is_list()` like logic, also now with an added check to handle those single key sub-arrays. From the unit testing perspective, the old tests works with only a single change where I had previously had one test intentionally using non-sequential integer keys. It wasn't based on a real-world situation, but I had it in there to verify my expectations. I don't believe it degrades any prior functionality.

It's getting to the point I'd like to do a logic refactor, but that might best wait until the change over to `<dl>` tags. Let me know what you think and if there is anything else you'd like to see.

**Comment by natecollins** [comment]
These code reviews are great, @demiankatz; thanks for double checking! It was likely me who wasn't thinking through things correctly : )

You are correct in how the those two cases should behave. The `"000"` case would be display because PHP would not cast that to an integer, per the [array key casting rules](https://www.php.net/manual/en/language.types.array.php). The single `0` index would not be displayed.

You were also right that the result of `isSingleIntegerKeyArray()` seems to have been logically redundant in one of its uses; that's been removed. The other uses appear important for handling the `['049' => ['value1']]` case to have `value1` show up as just the string value:
```
049: value1
```
versus
```
049:
  value1
```
I think that was the desired state. Let me know if that's not the case.

New revision is pushed. I've added several new test cases, including the ones you specified. I also renamed the class support functions to hopefully be more straightforward. Happy to keep refactoring as needed!

**Comment by demiankatz** [comment]
Thanks, @natecollins, I'm glad you're finding the reviews helpful rather than annoying. ;-) I do really enjoy GitHub collaboration -- this is miles ahead of the old days of sharing SVN patch files on JIRA!

In any case, I think this is more readable now, and it's doing what I want it to do, so I'm going to go ahead and merge it back into my main pull request, and then solicit another review or two there to be sure everybody's happy with the combined result.

Thanks again for all the work polishing this!

**Pull request merged**
